#!/bin/bash
domain=$1
subdomains=$2
if [ -z "$2" ]; then
subdomains=(www lb-01 web-01 web-02)
    
fi

print_line(){
    subdomain=$1
    record=$2
    result=$3
    echo "The subdomain $subdomain is a $record record and points to $result"
}


for subdomain in "${subdomains[@]}"; do
    result=$(dig +short "$subdomain"."$domain")

    
    if [ -n "$result" ]; then
        record=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        print_line "$subdomain" "$record" "$result"
    fi
done
