#!/usr/bin/env bash
# creates a script and kills it with SIGQUIT or SIGTERM

echo $$ > /var/run/myscript.pid

while true; do
echo "To infinity and beyond"
sleep 2
done

trap "Y U no love me?!" SIGINT
trap "I hate the kill command" SIGTERM
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT 