#!/usr/bin/env bash
# This script prints to infinity and beyond and I am inivicible when it recieves a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

while true; do

      echo "To infinity and beyond"
      
      sleep 2
      
done