#!/usr/bin/env bash
# This script prints Hi after the 9th iteration of printing Best School
n=0
while [ $n -ne 10 ];
do
    if [ $n == 9 ]; then
       	   echo "Hi"
    fi
    echo "Best School"
       ((n++))
done
