#!/usr/bin/env bash

useradd -d /var/www/html -s /sbin/nologin nginx
sed -i 's/user  nginx;/user  nginx;\n\tworker_processes  auto;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen [::]:8080;/g' /etc/nginx/sites-available/default
service nginx restart
