#!/usr/bin/env bash
#changing ngnix to run as nginx and listen to 8080
pkill -f apache2
sed -i s/80/8080/g /etc/nginx/sites-available/default
chmod -R 666 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
