#!/usr/bin/env bash

# Set the name of the private key
keyname="school"

# Set the number of bits in the key
keybits="4096"

# Set the passphrase fof the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $keybits -f $keyname -N "$passphrase"